default: &default
  adapter: postgresql
  encoding: unicode
  username: development
  password: development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: inteligov-api_development

test:
  <<: *default
  database: inteligov-api_test

production:
  <<: *default
  database: inteligov-api_production
  username: inteligov-api
  password: <%= ENV['INTELIGOV-API_DATABASE_PASSWORD'] %>
